# action.yml
name: 'Shopify Theme Check Reporter'
description: 'Runs Shopify Theme Check on Pull Requests and posts a formatted report comment on Pull Requests.'
author: 'ShopLab-Team' # Update with actual author/org

branding:
  icon: 'message-square' # Icon from https://feathericons.com/
  color: 'blue' # Color: purple, green, blue, yellow, orange, red, gray-dark

# Define inputs for the action
inputs:
  github-token:
    description: 'GitHub token for posting comments. Typically provide using secrets.GITHUB_TOKEN in the workflow.' # Corrected description
    required: true
  fail-on-warnings:
    description: 'Set to "true" to fail the action if warnings are found (in addition to errors).'
    required: false
    default: 'false'
  node-version:
    description: 'Node.js version to use for running the check (passed to actions/setup-node).'
    required: false
    default: '20.x'
  theme-check-package:
    description: 'The specific npm package version for theme check (e.g., @shopify/theme-check-node@latest).'
    required: false
    default: '@shopify/theme-check-node@latest'

# Define outputs from the action (populated by the Node.js script)
outputs:
  error-count:
    description: 'Number of errors found by theme check.'
    value: ${{ steps.theme_check_script.outputs.error_count }}
  warning-count:
    description: 'Number of warnings found by theme check.'
    value: ${{ steps.theme_check_script.outputs.warning_count }}
  comment-body-file:
    description: 'Path to the temporary file containing the generated comment body markdown.'
    value: ${{ steps.theme_check_script.outputs.comment_body_file }}
  fallback-comment-body:
    description: 'Fallback comment body used if the script failed to generate the report file.'
    value: ${{ steps.theme_check_script.outputs.fallback_comment_body }}

runs:
  using: "composite"
  steps:
    # Step 1: Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    # Step 2: Install Theme Check library into the user's checked-out code
    - name: Install Theme Check
      id: theme-check-install
      shell: bash
      run: |
        echo "Installing Theme Check version ${{ inputs.theme-check-package }}..."
        if [ -f package-lock.json ]; then
          npm ci || (echo "npm ci failed, trying npm install..." && npm install --no-audit --no-fund --legacy-peer-deps)
        else
           npm install --no-audit --no-fund --legacy-peer-deps
        fi
        npm install ${{ inputs.theme-check-package }} --no-save --legacy-peer-deps
        echo "Theme Check installation completed"

    # Step 3: Run the Node.js script (located within this action's repository)
    - name: Run Theme Check Script
      id: theme_check_script
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
        WORKSPACE_PATH: ${{ github.workspace }}
        REPO_URL: ${{ github.server_url }}/${{ github.repository }}
        COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
        RUN_ID: ${{ github.run_id }}
        FAIL_ON_WARNINGS: ${{ inputs.fail-on-warnings }}
      shell: bash
      run: node ${{ github.action_path }}/scripts/run-theme-check.js # Assumes script is in scripts/

    # Step 4: Post the report comment using outputs from the script step
    - name: Post Theme Check Report to PR
      uses: marocchino/sticky-pull-request-comment@v2
      if: always() && github.event_name == 'pull_request'
      with:
        path: ${{ steps.theme_check_script.outputs.comment_body_file }}
        message: ${{ steps.theme_check_script.outputs.fallback_comment_body }}
        header: shopify-theme-check-report # Specific header for this action
        GITHUB_TOKEN: ${{ inputs.github-token }} # Pass the token provided by the user